name: CI benchmarks

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmarks:
    if: |
      github.event_name == 'pull_request' &&
      contains(github.event.pull_request.labels.*.name, 'Run benchmarks')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sunpy repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          sudo apt-get install -y libopencv-dev
          python -m pip install --upgrade pip
          pip install asv virtualenv
      - name: Add machine info for ASV
        run: asv machine --yes
      - name: Run benchmarks
        env:
          OPENBLAS_NUM_THREADS: 1
          MKL_NUM_THREADS: 1
          OMP_NUM_THREADS: 1
          ASV_FACTOR: 1.1
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          COLUMNS: 150  # set a large terminal width so that large tables are rendered in 2D
        run: |
          ASV_OPTIONS="--split --show-stderr --factor $ASV_FACTOR --cpu-affinity 0"
          asv continuous $ASV_OPTIONS ${BASE_SHA} ${GITHUB_SHA}
